---
profiles:
  default:
    private_key: ""
    public_key: ""
    account: 
    rest_url: "https://fullnode.testnet.aptoslabs.com"
    faucet_url: "https://faucet.testnet.aptoslabs.com"
  main:
    private_key: ""
    public_key: ""
    account: 
    rest_url: "https://fullnode.mainnet.aptoslabs.com"
